# Generated by https://github.com/sre-norns/urth/blob/main/scripts/homebrew-formula.py
# for each stable release. Edit the template there: the next release overwrites
# changes made here.
class Urthctl < Formula
  desc "Command-line client for Urth synthetic monitoring"
  homepage "https://github.com/sre-norns/urth"
  version "0.1.0"
  license "PolyForm-Noncommercial-1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.0/urthctl_v0.1.0_darwin_arm64.tar.gz"
      sha256 "70c22fcbd4635bb9a38d51d91738810deab9f5368e2afa41a932959aef3627c2"
    end

    on_intel do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.0/urthctl_v0.1.0_darwin_amd64.tar.gz"
      sha256 "815af658b58f1184d7d7009793aa94c5ca70bfd9eef873075a37584be66edde1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.0/urthctl_v0.1.0_linux_arm64.tar.gz"
      sha256 "16ab53ac313bdec890fa6fde528d348488eafbe9e7a6c3279eb606f228951e16"
    end

    on_intel do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.0/urthctl_v0.1.0_linux_amd64.tar.gz"
      sha256 "729b4df180c129572d6ee3737b99e88d9102be4c8e3eda6bf93ee3f3341f6c3e"
    end
  end

  def install
    bin.install "urthctl"
  end

  test do
    assert_match "Urth Command line tool", shell_output("#{bin}/urthctl --help")
  end
end
