# Generated by https://github.com/sre-norns/urth/blob/main/scripts/homebrew-formula.py
# for each stable release. Edit the template there: the next release overwrites
# changes made here.
class Urthctl < Formula
  desc "Command-line client for Urth synthetic monitoring"
  homepage "https://github.com/sre-norns/urth"
  license "PolyForm-Noncommercial-1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.2/urthctl_v0.1.2_darwin_arm64.tar.gz"
      sha256 "7d71d0ed2767749feae259b5c1bab2e05005531b148775cdbc9b2efe886739a2"
    end

    on_intel do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.2/urthctl_v0.1.2_darwin_amd64.tar.gz"
      sha256 "ea7a6facaa262f3de22eb3da2fe66a5492458310f11914f90fbd9ba85ba606be"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.2/urthctl_v0.1.2_linux_arm64.tar.gz"
      sha256 "da2cff032e2c54fa61a0c3b3713ed1b55e83cd17f272a22cc94c06120baa4d03"
    end

    on_intel do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.2/urthctl_v0.1.2_linux_amd64.tar.gz"
      sha256 "c7430bc71d1150cc23ca74bf117ca9112353c8030dc29e27ae22f28e6f08538d"
    end
  end

  def install
    bin.install "urthctl"
  end

  test do
    assert_match "Urth Command line tool", shell_output("#{bin}/urthctl --help")
  end
end
