# Generated by https://github.com/sre-norns/urth/blob/main/scripts/homebrew-formula.py
# for each stable release. Edit the template there: the next release overwrites
# changes made here.
class Urthctl < Formula
  desc "Command-line client for Urth synthetic monitoring"
  homepage "https://github.com/sre-norns/urth"
  license "PolyForm-Noncommercial-1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.1/urthctl_v0.1.1_darwin_arm64.tar.gz"
      sha256 "f45a9025104a85249dbd62db437ca96b313d702f1043c1e700af2b0af581b1f6"
    end

    on_intel do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.1/urthctl_v0.1.1_darwin_amd64.tar.gz"
      sha256 "a06761fe9e67c90e8518e8e6a8ebbbfa3c6b573370a2dc533402fb8e1ab16f76"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.1/urthctl_v0.1.1_linux_arm64.tar.gz"
      sha256 "cfa1e814c9842fa02e0c312080875c22253e0f1444998fcedc8e1e0eddf71dcc"
    end

    on_intel do
      url "https://github.com/sre-norns/urth/releases/download/v0.1.1/urthctl_v0.1.1_linux_amd64.tar.gz"
      sha256 "b7dc9bfa67530a938c6e72fc1e0eeb19aded3e8515d01360b2cc8d2dc14aea44"
    end
  end

  def install
    bin.install "urthctl"
  end

  test do
    assert_match "Urth Command line tool", shell_output("#{bin}/urthctl --help")
  end
end
